services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    env_file: .env
    volumes:
      - ./vw-data:/data/
    networks:
      - tailscale-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  caddy:
    image: caddy:2-alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
    networks:
      - tailscale-net
    restart: unless-stopped
    depends_on:
      - vaultwarden

networks:
  tailscale-net:
    driver: bridge
