services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file: .env
    volumes:
      - ./vw-data:/data/
    networks:
      - tailscale-net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  caddy:
    build: ./caddy-dockerfile
    ports:
      - "127.0.0.1:8080:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
    networks:
      - tailscale-net
    restart: unless-stopped
    depends_on:
      - vaultwarden
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}

networks:
  tailscale-net:
    driver: bridge
